version: "3.7"
services:
  config-server:
    image: config-server:v1
    ports:
      - "8888:8888"
    restart: always
    networks:
      - springcloud
  eureka-server:
    image: eureka-server:v1
    ports:
      - "8761:8761"
    restart: always
    networks:
      - springcloud
  mysql-microservices:
    image: mysql-microservices:5.7
    ports:
      - "3306:3306"
    restart: always
    networks:
      - springcloud
    environment:
      MYSQL_DATABASE: db_cloud_spring
      MYSQL_ROOT_PASSWORD: password
  postgres-microservices:
    image: postgres-microservices:12-alpine
    ports:
      - "5432:5432"
    restart: always
    networks:
      - springcloud
    environment:
      POSTGRES_DB: db_spring_cloud
      POSTGRES_PASSWORD: password
  products-service:
    image: products-service:v1
    restart: always
    networks:
      - springcloud
    depends_on:
      - config-server
      - eureka-server
      - mysql-microservices
  items-service:
    image: items-service:v1
    ports:
      - "8002:8002"
      - "80058005"
      - "8007:8007"
    restart: always
    networks:
      - springcloud
    depends_on:
      - config-server
      - eureka-server
      - products-service
  users-service:
    image: users-service:v1
    restart: always
    networks:
      - springcloud
    depends_on:
      - config-server
      - eureka-server
      - postgres-microservices
  oauth-service:
    image: oauth-service:v1
    ports:
      - "9300:9300"
    restart: always
    networks:
      - springcloud
    depends_on:
      - config-server
      - eureka-server
      - users-service
  zuul-server:
    image: zuul-server:v1
    ports:
      - "8090:8090"
    restart: always
    networks:
      - springcloud
    depends_on:
      - config-server
      - eureka-server
      - products-service
      - items-service
      - users-service
      - oauth-service
  rabbitmq-microservices:
    image: rabbitmq-microservices:v1
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    networks:
      - springcloud
  zipkin-server:
    image: zipkin-server:1
    ports:
      - "9411:9411"
    restart: always
    networks:
      - springcloud
    depends_on:
      - rabbitmq-microservices
      - mysql-microservices
    environment:
      RABBIT_ADDRESSES: rabbitmq-microservices:5672
      STORAGE_TYPE: mysql
      MYSQL_USER: root
      MYSQL_PASS: password
      MYSQL_HOST: mysql-microservices
networks:
  springcloud:
